services:

  web-app:
    profiles: [container, webapp]
    build:
      context: .
      dockerfile: Dockerfile.minideb
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - LLM=${LLM}
      - HTTP_PORT=8888
      # host.docker.internal: listening the host from the container
    ports:
      - 8888:8888
