services:

  web-app:
    profiles: [container, webapp]
    build:
      context: .
      dockerfile: Dockerfile.minideb
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - LLM=${LLM}
      - HTTP_PORT=${HTTP_PORT}
      # host.docker.internal: listening the host from the container
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
